### ISSUE TITLE
a  A small request

### ISSUE THREAD

**Issue by COST-97** [cics-nd/ar-pde-cnn#2]
What principles do `tsteps` and `tback` implement in the program? 
Could you give me some advice?
 Thank you very much!

**Comment by NickGeneva** [comment]
Hi, I am not sure if you ended up figuring this out since the issue is closed. However, just to make sure...

tsteps: This parameter simply controls how many time-steps of the system the model predicts. This is progressively increased during training to allow the model to first learn the physics close to the initial state and then discover physics later in time as training continues. Not performing this unrolling makes training a lot more difficult in my experience.

tback: This parameter controls the stride at which we perform back-prop. Back-prop through time helps learn a continuous time-series (just like with RNNs and LSTMs) however too many steps result in a vanishing gradient it seems with a drop in performance. Should be tuned at the end of the day depending on the model used.

Details regarding these ideas are ellaborated further in the paper in [Section 3.2](https://arxiv.org/pdf/1906.05747.pdf).
